![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.arange(0,10)
print(my_array[::-2])

[9 7 5 3 1]


In [4]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


In [5]:
np.flip(my_array[my_array % 2 == 1])

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [6]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(my_array[-2:-4:-1])

[8 7]


In [10]:
print(my_array[(my_array > 6) & (my_array <= 8)][::-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [11]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
print(my_array[2::-1])

[2 1 0]


In [14]:
print(my_array[my_array <= 2][::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [17]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
print(my_matrix.T)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [19]:
print(np.transpose(my_matrix))

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [20]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [21]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [22]:
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [40]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


In [31]:
np.vsplit(my_matrix, [2])

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])]

In [37]:
np.hsplit(np.vsplit(my_matrix, [2])[0], [2])[0]

array([[1, 2],
       [6, 7]])

In [42]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [46]:
new_matrix = my_matrix[:2,:2].copy()
print(new_matrix)

[[0 2]
 [6 7]]


In [47]:
new_matrix[0,0] = 0
print(new_matrix)
print(my_matrix)

[[0 2]
 [6 7]]
[[ 0  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [49]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [50]:
print(my_matrix[::2, ::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [51]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [53]:
print(my_matrix[:3, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [54]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [55]:
x == "Loro"

array([ True, False, False,  True, False])

In [56]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [57]:
np.where(x == "Loro")

(array([0, 3], dtype=int64),)

In [58]:
x[np.where(x == "Loro")[0]]

array(['Loro', 'Loro'], dtype='<U5')

In [61]:
np.where(x == "Loro", x, "")

array(['Loro', '', '', 'Loro', ''], dtype='<U5')

In [62]:
np.extract(x == "Loro", x)

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [63]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [64]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [65]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print(x.itemsize) # Cada valor tiene reservado 8 bytes
print(x.nbytes) # Los 10 valores tienen reservados 8 * 10 valores = 80 bytes
print(x.dtype) # Cada valor tiene reservado 8 bytes * 8 bits = 64 bits

8
80
float64


In [70]:
2 ** 64

18446744073709551616

In [72]:
x = np.full(10, 0)
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [74]:
print(x.itemsize) # Cada valor tiene reservado 4 bytes
print(x.nbytes) # Los 10 valores tienen reservados 4 * 10 valores = 40 bytes
print(x.dtype) # Cada valor tiene reservado 4 bytes * 8 bits = 32 bits

4
40
int32


In [77]:
x = np.full(10, 0, dtype=np.int8)
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [79]:
print(x.itemsize) # Cada valor tiene reservado 1 bytes
print(x.nbytes) # Los 10 valores tienen reservados 1 * 10 valores = 40 bytes
print(x.dtype) # Cada valor tiene reservado 1 bytes * 8 bits = 16 bits

1
10
int8


In [80]:
2 ** 8

256

In [ ]:
# -128:127

In [92]:
x[0] = 128
print(x)

[-128    0    0    0    0    0    0    0    0    0]


C:\Users\Miguel Angel\AppData\Local\Temp\ipykernel_8408\747219263.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  x[0] = 128


In [ ]:
# 00000001 = -127
# 00000000 = -128
# 11111111 = -129 = 127

In [ ]:
# 11111110 = 126
# 11111111 = 127
# 00000000 = 128 = -128

## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [93]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [94]:
np.flip(x)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [95]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [98]:
ejer_12 = np.array([1,2,0,0,4,0])
print(ejer_12)

[1 2 0 0 4 0]


In [101]:
np.where(ejer_12 != 0)

(array([0, 1, 4], dtype=int64),)

In [104]:
np.where(ejer_12 != 0)[0]

array([0, 1, 4], dtype=int64)

In [103]:
ejer_12[np.where(ejer_12 != 0)[0]]

array([1, 2, 4])

In [105]:
def f_ejer_12(vector):
    return vector[np.where(vector != 0)[0]]

In [107]:
vector_e = np.array([1,0,0,4,4,0])
vector_s = f_ejer_12(vector_e)
print(vector_s)

[1 4 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [9]:
x = np.random.randint(100, size=(10,10))
print(x)

[[88 92 70 88 69 11 19 66 56 94]
 [22 30 24 55 23  8 76 18 19 17]
 [89 24 76  5 81 90 51 73 24 71]
 [39 36 92 45 72 66 88 43 71 12]
 [93 75 93 17 57 57 61  5 88 16]
 [77  7 27 17 77 12 35 65 73 33]
 [55 20 81 85  6 60 28 92 99 41]
 [10 12  2 22 67 41 74 17 30 84]
 [91 71 37 83 13 39 53 70 40 38]
 [78 79 82  8 54 75 55 43  3  6]]


In [17]:
print("Mínimo", np.min(x), x.min())
print("Máximo", np.max(x), x.max())
print("Sum", np.sum(x), x.sum())
print("Media", np.mean(x), x.mean())
print("Mediana", np.median(x))

Mínimo 2 2
Máximo 99 99
Sum 5022 5022
Media 50.22 50.22
Mediana 54.5


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [73]:
np.random.seed(749302)
x = np.random.random(30)
print(x)
print(x.mean())
print(x.sum()/x.size)

[0.19115569 0.02379983 0.15233136 0.01628044 0.44902786 0.31502517
 0.81548117 0.26501091 0.09806833 0.80636974 0.52865217 0.53935316
 0.75587051 0.70325909 0.81560245 0.23462212 0.16090058 0.57234264
 0.07453135 0.69427772 0.6321447  0.1123546  0.82472768 0.73558116
 0.6594625  0.95364769 0.78329897 0.56482587 0.18374005 0.69463067]
0.47854587319555875
0.47854587319555875


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [75]:
ejer_15 = np.full((10,10), 1)
print(ejer_15)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [76]:
ejer_15[1:-1, 1:-1] = 0
print(ejer_15)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [79]:
ejer_15 = np.full((10,10), 0)
print(ejer_15)
ejer_15[::len(ejer_15)-1, ::] = 1
ejer_15[::, ::len(ejer_15)-1] = 1
print(ejer_15)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [92]:
def f_ejer_15(tamaño:tuple=(10,10), contorno=1, relleno=0):
    ejer_15 = np.full(tamaño, contorno)
    ejer_15[1:-1, 1:-1] = relleno
    return ejer_15

In [93]:
f_ejer_15()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [86]:
f_ejer_15((3,3))

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [87]:
f_ejer_15((7,7))

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [88]:
f_ejer_15((2,2))

array([[1, 1],
       [1, 1]])

In [91]:
f_ejer_15((8,8), "A", "B")

array([['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
       ['A', 'B', 'B', 'B', 'B', 'B', 'B', 'A'],
       ['A', 'B', 'B', 'B', 'B', 'B', 'B', 'A'],
       ['A', 'B', 'B', 'B', 'B', 'B', 'B', 'A'],
       ['A', 'B', 'B', 'B', 'B', 'B', 'B', 'A'],
       ['A', 'B', 'B', 'B', 'B', 'B', 'B', 'A'],
       ['A', 'B', 'B', 'B', 'B', 'B', 'B', 'A'],
       ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A']], dtype='<U1')

## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [94]:
x = np.full((8,8), 0)
print(x)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [95]:
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [100]:
y = np.array([[0,1], 
              [1,0]])

np.concatenate((y,y))

array([[0, 1],
       [1, 0],
       [0, 1],
       [1, 0]])

## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [ ]:
y = np.array([[0,1], 
              [1,0]])

In [101]:
x = np.tile(y, (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [105]:
y = np.array([[0,1]])
np.concatenate((y, y[::,::-1]))

array([[0, 1],
       [1, 0]])

## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [106]:
x = np.random.randint(1,20, (5,5))
print(x)

[[17  9  8 17  6]
 [ 4  4 17 10 17]
 [17  3 15 16  3]
 [ 4  1 12  8 17]
 [ 4  5 11  4  5]]


In [108]:
np.mean(x)

9.36

In [109]:
np.std(x)

5.599142791535146

In [110]:
x_norm = (x - np.mean(x)) / np.std(x)
x_norm

array([[ 1.36449458, -0.06429556, -0.24289432,  1.36449458, -0.60009186],
       [-0.95728939, -0.95728939,  1.36449458,  0.11430321,  1.36449458],
       [ 1.36449458, -1.13588816,  1.00729705,  1.18589581, -1.13588816],
       [-0.95728939, -1.49308569,  0.47150075, -0.24289432,  1.36449458],
       [-0.95728939, -0.77869063,  0.29290198, -0.95728939, -0.77869063]])

In [111]:
x_norm.mean()

7.993605777301127e-17

In [112]:
x_norm.std()

1.0

## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [114]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [116]:
y = x.copy()
y[(y >= 3) & (y <= 8)] = -1
print(y)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [117]:
z = x.copy()
np.where((z >= 3) & (z <= 8), z * (-1), z)

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

In [118]:
z = x.copy()
np.where(~(z >= 3) | ~(z <= 8), z, z * (-1))

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])